export type DRAW_CARD_ISSUED = "DRAW_CARD_ISSUED";
export const DRAW_CARD_ISSUED = "DRAW_CARD_ISSUED";
export type DRAW_CARD_ACCEPTED = "DRAW_CARD_ACCEPTED";
export const DRAW_CARD_ACCEPTED = "DRAW_CARD_ACCEPTED";
export type DRAW_CARD_DECLINED = "DRAW_CARD_DECLINED";
export const DRAW_CARD_DECLINED = "DRAW_CARD_DECLINED";

export type MOUSE_ON_CARD = "MOUSE_ON_CARD";
export const MOUSE_ON_CARD = "MOUSE_ON_CARD";
export type MOUSE_OFF_CARD = "MOUSE_ON_CARD";
export const MOUSE_OFF_CARD = "MOUSE_ON_CARD";