export type DRAW_CARD_ISSUED = "DRAW_CARD_ISSUED";
export const DRAW_CARD_ISSUED = "DRAW_CARD_ISSUED";
export type DRAW_CARD_ACCEPTED = "DRAW_CARD_ACCEPTED";
export const DRAW_CARD_ACCEPTED = "DRAW_CARD_ACCEPTED";
export type DRAW_CARD_DECLINED = "DRAW_CARD_DECLINED";
export const DRAW_CARD_DECLINED = "DRAW_CARD_DECLINED";

export type MOUSE_ON_CARD = "MOUSE_ON_CARD";
export const MOUSE_ON_CARD = "MOUSE_ON_CARD";
export type MOUSE_OFF_CARD = "MOUSE_ON_CARD";
export const MOUSE_OFF_CARD = "MOUSE_ON_CARD";

export type MOUSE_ON_SUMMONING = "MOUSE_ON_SUMMONING";
export const MOUSE_ON_SUMMONING = "MOUSE_ON_SUMMONING";
export type MOUSE_OFF_SUMMONING = "MOUSE_ON_SUMMONING";
export const MOUSE_OFF_SUMMONING = "MOUSE_ON_SUMMONING";

export type CARD_DRAGGED = "CARD_DRAGGED";
export const CARD_DRAGGED = "CARD_DRAGGED";
export type SUMMONING_ISSUED = "SUMMONING_ISSUED";
export const SUMMONING_ISSUED = "SUMMONING_ISSUED";
export type SUMMONING_ACCEPTED = "SUMMONING_ACCEPTED";
export const SUMMONING_ACCEPTED = "SUMMONING_ACCEPTED";
export type SUMMONING_DECLINED = "SUMMONING_DECLINED";
export const SUMMONING_DECLINED = "SUMMONING_DECLINED";
