version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JAVA_OPTS: -Xms512m -Xmx3072m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "backend/build.gradle.kts" }}
          - v1-dependencies-{{ checksum "webapp/build.gradle.kts" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew test

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "backend/build.gradle.kts" }}

      - run: ./gradlew build --info -x test

      - run: ./gradlew npmInstall

      - save_cache:
          paths:
            - ~/repo/webapp/node_modules
          key: v1-dependencies-{{ checksum "webapp/build.gradle.kts" }}
